### ISSUE TITLE
HQ props: lost campfire

### ISSUE THREAD

**Issue by Warhammer47** [LordGolias/antistasi#160]
**Version: develop
Mods: ACE
Mode: MP**

After arriving at the HQ noticed that no campfire was there and the reset HQ position wasn't working.

**Comment by LordGolias** [comment]
No idea why the fireplace was not there. The reset HQ position is now working (bce9b9111fd1c71272100d070a5b9a383b43163a). When you pressed it, there was an error on the log, right? (in SP it shows the black box with the error). Next time, please try to include the error here. Otherwise, I will have to spend time understanding why it fails.
