### ISSUE TITLE
Wrongly read `AAFsupport` from a location of type `base`

### ISSUE THREAD

**Issue by SomethingSimpl** [LordGolias/antistasi#36]
From my latest play session, feel free to disregard if they dont mean anything:

`11:20:02 "[AS] Error: object_get(location,AS_base_11,AAFsupport): property 'AAFsupport' does not exist for object 'AS_base_11' in container 'location'. Valid properties: [""_properties"",""type"",""position"",""side"",""busy"",""garrison"",""spawned"",""forced_spawned"",""size""]"`

**Comment by LordGolias** [comment]
It is an error. We are trying to get the property `AAFsupport` of a base (`AS_base_11`), but that property only exists for cities. This means that somewhere we are running code for a city on a base. :)

I would try to search for `AAFsupport` and double check where a base may wrongly be used instead of a city (or else)

**Comment by SomethingSimpl** [comment]
Yeah, that s in the title was a mistype. Thanks for the explanation though, still learning from your fixes :)

**Comment by LordGolias** [comment]
I confirm that this is still present in v0.1.

**Comment by LordGolias** [comment]
Reopening: this is not fixed yet. See #120

**Comment by LordGolias** [comment]
Found which code was calling this wrongly.
