### ISSUE TITLE
Test new save system

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#45]
@Warhammer47 and @SomethingSimpl, the last set of 20 or so commits dramatically changes the saved system by unifying the different bits and pieces of saving a game (incompatible with old saves!, it will error to load a old saved game).

The most pleasant feature of this is that we can now save a game into a file. For example, the players are saved as 

```
%%%#>OB:{_sp_player_:OB:{garage:AR:[]
%%%#>score:SC:25
%%%#>rank:ST:"PRIVATE"
%%%#>money:SC:100}
```

SC means scalar, ST means string, OB:{} means nested, etc.

When we press save game, the save is generated on the server and copied to the clipboard of every client and also stored in the commander's profile as before. Likewise, there is now a button to load a game from the clipboard (commander).

This allow us to easily share saved games and to modify them if the save structure changes or there was an error.

It would be great to have this heavily tested, as it is a very important part of the mission. 

1. Any case where it breaks?
2. Does it fixes #20, #17 and #35?

There is an existing error: #44

Be aware that this save structure is still not definitive, it will likely change 1 more time for a minor but important adjustment. There will be a release when the structure of the saved game is frozen.

**Comment by mike-187** [comment]
Hi, will this server side savesystem work on linux server as well? I can test this weekend and come back to you.
-mike

**Comment by StefArma** [comment]
I can run a test on server as well. What should i exactly look for? maybe i try different moment run the save and check if the created file store all infos correctly?

**Comment by LordGolias** [comment]
@mike-187, yes, it should work (thanks for testing it on Linux!). The de/serialization happens on the Arma engine, so it should be independent of the OS. The file does contain windows endings (`\r\n`) that are necessary to deserialisation, so make sure that if you modify the file string, the string that you copy back to Arma has `\r\n`. :)

@StefArma, we can try to test first the open issues I identified above to confirm that they were fixed. E.g. confirm that the FIA garage is saved and loaded correctly. Thanks a lot for the help!

**Comment by mike-187** [comment]
@LordGolias hi, so did a quick test... on dedicated Linux server it is not completing the save game...
I just tried to start new mission on Altis and just tried to save the game right away.
on the server in the log file it finishes and says "[AS] Server: game saved." at the end but in Arma on the client the Save Game prompt never ends. I even did let it run for 15 mins or so. Nothing changed.
Hope it helps I uploaded here the server log from the quick test > https://pastebin.com/JqxpQVFk

When I just host it in MP game it works and it saves it to clipboard and to the file successfully. 
My question is where does it save on the server? On the original antistasi mission it would save the progress to the server profile i.e. servername.vars.Arma3Profile file.

last question :) do you have a discord server where you guys discuss your version of Antistasi?
--Mike

**Comment by StefArma** [comment]
dedicated Windows server it's not completing the save game as well.

My toughts about different kind of servers/users.
1) Open community: it's probably our case only so far,  i can play with people at night, then the next day other people wanna continue play and they can't because only we've the save. Workaround might be Dropbox but not really an immediate thing.

2) Closed community (clan): they probably wanna have control over thier own mission so that they get advantage that nooneelse can start from their save and mess up things. In addition they have the benefit they can leave the server open for potential people who wanna play their own stuff while they're not playing their campaign.

3) User hosting and SP, no issues at all, on the contrary very good way to handle the save.

Can't give an appropriate suggestion for the open community case because i don't know what it is actually possible and worth to do.
We're using inidbi2 mod serverside only that allow store each savegame (from ingame it always load the last)  and also playerstat, so that everyone who connect mantain his money,rank and gears(gears only if logged out within 100m from HQ otherwise respawn naked).

**Comment by LordGolias** [comment]
@mike-187, saving a game should take 5s tops. It is a bug. 

Regarding the saved games location: currently, anyone can become a commander, which means that someone could remove all saved games. For this reason, any interaction with saved games is limited to local changes- Specifically, the following happens:

1. server serializes game to a string (`AS_fnc_saveGame`)
2. server sends the string to all clients
3. every client receives the string (`AS_fnc_receiveSavedData`) and copies it to clipboard
4. if the client is the commander, the string is stored in the player's profile under the save name he decided when saving

Bear with me, this will change once the server membership is re-introduced, as it will make sure players that modify the server data are white-listed by the server's admin.

**Comment by LordGolias** [comment]
@mike-187 and @StefArma, I reproduce the issue you mentioned, and fixed it in 6c866bfc6b185b6af91912eb7e49a0a9b8328e70. Thank you for the help on this.

**Comment by LordGolias** [comment]
@mike-187, regarding the discord, I haven't though about it. Here you go: https://discord.gg/3Wc49N not sure it will work, for now it is a test to see whether it is necessary or not.

**Comment by LordGolias** [comment]
Thank you all for the reported issues! I will close this for now and ask you to report issues as usual on github.
