### ISSUE TITLE
Vehicle recruitment empty list and more issues on dedicated server

### ISSUE THREAD

**Issue by JohnnyDeeee** [LordGolias/antistasi#5]
Hi,

I like the version you made, but some things kinda brake on my dedicated server...
- Vehicle recruitment is empty
- Unit recruitment have prices listed as "any$"
- After choosing HQ location, the hq 'items' are not moved to the new location (you can move them with the maintenance->reset hq items option)
- The load button doesnt do anything...

All of these things dont happen when i run the mission from the editor->run as MP

I'm using the master branch btw.

**Comment by LordGolias** [comment]
Thanks for bringing this up. You are correct, I haven't worked out the details of a dedicated env yet. 

I know what to do, it is just not worked out.

**Comment by JohnnyDeeee** [comment]
Can you give an estimate when this will be implemented?
Currently i'm playing the 1.7.5 (beta) version from the official Antistasi with a group of friends, but it would be cool if we could switch to your version.

**Comment by LordGolias** [comment]
I had never tried this version on a dedicated env (also because I didn't know how to set it up).

Currently, I am rewriting all current missions to a new mission system that 

1. uses less code (atm, 3470 insertions, 5016 deletions), easier to maintain
2. knows how to store missions persistently such that when the game is loaded, the ongoing missions are restarted
3. missions are selected from a list of currently *available* missions, also shown on a map.
4. mission resources (units, vehicles) are spawned by any connected machine (and not only by the server).

This will prob take 2-3 more weeks. I will approach the dedicated env after that. That should take more 1-2 weeks. So, in total, at least 1 more month.

I am sorry that the dedicated is not working. Have you tried non-dedicated? With 4 players it runs smoothly on my machine (i5).

**Comment by JohnnyDeeee** [comment]
Ah i see..
Well i guess it works fine on a non-dedicated system, but we preffer to have it running on a dedi. This way people can join in whenever they feel like (and i do not have the resources to setup a non-dedi pc for 24/7)

If you want i can take a look at the code and find out what goes wrong where and start a fork, but i'll need some time to get fammilliar with the overall code and that may take some time..

**Comment by LordGolias** [comment]
Thanks @JohnnyDeeee, I totally agree with you that it is expected for this to work on dedicated env, and having a stable version for every env is a requirement to publish this e.g. on steam.

I made sure to put several tests on the scripts so arguments are reasonable. The first step to debug would be to look at the logs and search for either SQF errors or log entries starting with `[AS]`.

Regarding the code, I made a huge effort to document code and keep everything I touch better than it was left. The README contains a short summary of some of the components and how they work. If you have specific questions you can ask me in discord Golias #2739. If you are interested in a general overview of the code, we can arrange a discord call and I describe it to you.

**Comment by JohnnyDeeee** [comment]
I started creating issues regarding the Dedicated server setup. I guess we can close this one to keep things neat and organized.
