### ISSUE TITLE
Re-add and test TFAR.

### ISSUE THREAD

**Issue by LordGolias** [LordGolias/antistasi#88]
With the overall change, TFAR support was dropped (it may work, but I was not checking it did). Let us aim at re-adding it.

**Comment by StefArma** [comment]
Going to test asap,

also.. how did you handled the default channel syncronization without CBA dependency?

**Comment by LordGolias** [comment]
@StefArma. Great. 

Regarding channel sync. I do not know. What is that? :P

**Comment by StefArma** [comment]
I'm happy you're back LordGolias! this issue can be closed by https://github.com/A3Antistasi/antistasiofficial/wiki/Dedicated-server-setup#syncronize-tfar-fequencies 

In that way everyone on channel 1 will have same radiofrequency so people can just change channel instead of setting an unique frequency every time
